### ISSUE TITLE
[unrelated to slack-archiver] VSCode remote with NODE_EXTRA_CA_CERTS

### ISSUE THREAD

**Issue by kiranpradeep** [gartnera/slack-archiver#1]
Sorry to raise an issue unrelated to this repository. I could not find other means to contact you and the original issue is locked to colloborators. This is only a request, kindly ignore if not appropriate. Thanks in advance.

In vscode remote issue [[98](https://github.com/microsoft/vscode-remote-release/issues/98#issuecomment-489679447)], you mentioed about using NODE_EXTRA_CA_CERTS to temporarily fix the issue. I am using remote development in docker with vs-code[[2](https://code.visualstudio.com/docs/remote/containers#_quick-start-try-a-dev-container)].

1. I like to know in which machine or environment did you set NODE_EXTRA_CA_CERTS - Local OS or Remote OS?
2. Which file or environment did you set this variable?

**Comment by gartnera** [comment]
You would set this on the remote server. I set it in `/etc/environment`, but you could set it in a variety of places (`.bashrc`).
